### ISSUE TITLE
Possible malformed metadata

### ISSUE THREAD

**Issue by ythecombinator** [jtbandes/Metalbrot.playground#3]
I've cloned your repo through `git` but when I get to open, *XCode* tells me:

<img width="332" alt="captura de tela 2017-03-14 as 00 47 57" src="https://cloud.githubusercontent.com/assets/2644563/23885126/0db0a27c-0850-11e7-92f8-99e0c59cd12f.png">

Any ideas on what's going on?

**Comment by jtbandes** [comment]
I've never seen this error before. Have you tried downloading the zipped playground from https://github.com/jtbandes/Metalbrot.playground/releases?

**Comment by algal** [comment]
For what it's worth, I see exactly the same error when trying to clone the repo's source code, but it works fine when I download the zip.

**Comment by jtbandes** [comment]
Ah, I think I see what the problem is: since the repo is _named_ Metalbrot.playground, it looks like a playground bundle, but the actual playground file is _inside_ the top-level directory. I'll fix this by renaming the repo.
